title: "Lin Zhou's Homepage"
page-top-title: "Lin Zhou"
top-section-bg-text: "Computer Vision & Communication"
home-subtitle: "Lin Zhou&ensp;|&ensp;周琳"
copyright-text: '&copy; Lin Zhou 2026. All Rights Reserved.'